-- Hand-written migration. Phase 0B spec §3.8, §6.3.3, §6.4, §6.5.
--
-- Every statement here is one no ORM can express, and each names the invariant
-- it enforces. Partial indexes are NOT in this file: they are declared in
-- schema.prisma and generated by Prisma Migrate (§6.5, test D13).
--
-- ┌─ SPEC CONFLICT, REPORTED NOT RESOLVED ────────────────────────────────┐
-- │ §3.8 and §6.5 authorize hand-written SQL for "exactly two things":    │
-- │ the ledger role grants and the two subtype-family CHECK constraints.  │
-- │ But §6.4 ALSO requires `CHECK (rosterCapacity BETWEEN 1 AND 5)` for   │
-- │ invariant I2, which is a third. The two sections disagree about the   │
-- │ count; §6.4's invariant table is the one that names an enforcement    │
-- │ mechanism for a LOCKED BY PRODUCT rule, so it is implemented here.    │
-- │ This is raised for the reviewer rather than resolved by editing the   │
-- │ approved specification. Nothing about the invariants themselves is in │
-- │ doubt — only §3.8/§6.5's arithmetic.                                  │
-- └───────────────────────────────────────────────────────────────────────┘

-- ═══════════════════════════════════════════════════════════════════════════
-- §6.3.3 — Activity root / subtype family integrity
--
-- Each subtype already carries a `family` column chained to Activity(id, ...)
-- by a composite foreign key, so it can never disagree with its root. These
-- two CHECKs pin that column to the one constant the subtype is for, which
-- makes WRONG-FAMILY unrepresentable (D15) and BOTH-SUBTYPES-PRESENT
-- unrepresentable with it (D16): a SESSION_BOUND root cannot carry a
-- SkillTrainingActivity, because that row's CHECK demands WALL_CLOCK while its
-- foreign key demands the root agree, and both cannot hold.
--
-- Deleting them costs only TIMING, never coverage: the §6.3.3 startup sweep is
-- written per family and is exhaustive over all four invalid states on its own.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE "SessionBoundActivity"
  ADD CONSTRAINT "SessionBoundActivity_family_is_session_bound"
  CHECK ("family" = 'SESSION_BOUND');

ALTER TABLE "SkillTrainingActivity"
  ADD CONSTRAINT "SkillTrainingActivity_family_is_wall_clock"
  CHECK ("family" = 'WALL_CLOCK');

-- ═══════════════════════════════════════════════════════════════════════════
-- I2 (§6.4) — count(playable characters) <= rosterCapacity <= 5
--
-- The CHECK enforces the BOUNDS. The count is verified inside the creating
-- transaction, because a count cannot be a column constraint (test D8).
-- LOCKED BY PRODUCT: DOMAIN_MODEL.md §5.4.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE "Account"
  ADD CONSTRAINT "Account_rosterCapacity_within_bounds"
  CHECK ("rosterCapacity" BETWEEN 1 AND 5);

-- ═══════════════════════════════════════════════════════════════════════════
-- I6 (§6.4, ADR-003) — the ledger is append-only
--
-- A database PERMISSION, not a schema object. No ORM models it, and this is
-- what makes the append-only guarantee true for a developer who has never read
-- ADR-003: the application role simply has no UPDATE or DELETE to issue.
--
-- The role is created NOLOGIN if it does not exist, so this migration is
-- self-contained and testable. Deployment attaches LOGIN and a password
-- separately — a migration has no business holding a credential.
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'globalidle_app') THEN
    CREATE ROLE "globalidle_app" NOLOGIN;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO "globalidle_app";

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public
  TO "globalidle_app";

-- The whole point. Revoked AFTER the blanket grant above, so ordering cannot
-- silently restore it.
REVOKE UPDATE, DELETE ON "LedgerEntry" FROM "globalidle_app";

-- Future tables default to the same shape. Without this, a table added by a
-- later migration would be unreachable by the application role.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "globalidle_app";
